### ISSUE TITLE
Running in Windows

### ISSUE THREAD

**Issue by johnomahen79** [HDI-Project/ATMSeer#25]
Do you have any shell scripts or mechanisms that will run in windows?  Or do I need to do this in a linux system?

**Comment by johnomahen79** [comment]
Disregard...sorry Pilot error....i thought I had ran vagrant up and had not....sorry

**Comment by johnomahen79** [comment]
Question...have you ever had an issue creating  the /vagrant/venv/bin/activate directory?  That is where I do fail

**Comment by johnomahen79** [comment]
And now I get
 Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => C:/atmseer/ATMSeer
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always willstill run.
 Preparing to unpack .../python_2.7.12-1~16.04_amd64.deb ...
    default: Unpacking python (2.7.12-1~16.04) ...
    default: Selecting previously unselected package nodejs.
    default: Preparing to unpack .../nodejs_12.4.0-1nodesource1_amd64.deb ...
    default: Unpacking nodejs (12.4.0-1nodesource1) ...
    default: Processing triggers for man-db (2.7.5-1) ...
    default: Setting up libpython2.7-stdlib:amd64 (2.7.12-1ubuntu0~16.04.4) ...
    default: Setting up python2.7 (2.7.12-1ubuntu0~16.04.4) ...
    default: Setting up libpython-stdlib:amd64 (2.7.12-1~16.04) ...
    default: Setting up python (2.7.12-1~16.04) ...
    default: Setting up nodejs (12.4.0-1nodesource1) ...
    default: npm
    default:
    default: WARN
    default:
    default: optional
    default:  SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
    default: npm
    default:
    default: WARN
    default:
    default: notsup
    default:  SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    default: npm
    default:
    default: ERR!
    default:  Maximum call stack size exceeded
    default:
    default: npm
    default:  ERR!
    default:  A complete log of this run can be found in:
    default: npm ERR!     /root/.npm/_logs/2019-06-12T14_29_00_343Z-debug.log
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'ubuntu/xenial64' version '20190605.0.0' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Vagrant has detected a configuration issue which exposes a
==> default: vulnerability with the installed version of VirtualBox. The
==> default: current guest is configured to use an E1000 NIC type for a
==> default: network adapter which is vulnerable in this version of VirtualBox.
==> default: Ensure the guest is trusted to use this configuration or update
==> default: the NIC type using one of the methods below:
==> default:
==> default:   https://www.vagrantup.com/docs/virtualbox/configuration.html#default-nic-type
==> default:   https://www.vagrantup.com/docs/virtualbox/networking.html#virtualbox-nic-type
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 7777 (guest) => 7777 (host) (adapter 1)
    default: 7779 (guest) => 7779 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => C:/atmseer/ATMSeer
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always willstill run.
==> default: Running provisioner: vagrantstart (shell)...
    default: Running: C:/Users/username/AppData/Local/Temp/vagrant-shell20190612-11896-1d7aofm.sh
    default: sh: 1: cross-env: not found
    default: npm
    default:  ERR! file sh
    default: npm ERR!
    default:
    default: code ELIFECYCLE
    default: npm ERR! errno
    default:  ENOENT
    default: npm
    default: ERR! syscall
    default:  spawn
    default: npm ERR! vis_atm@0.1.0 start: `cross-env PORT=7779 react-scripts-ts start`
    default: npm ERR! spawn ENOENT
    default: npm ERR!
    default:
    default: npm
    default:  ERR! Failed at the vis_atm@0.1.0 start script.
    default: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    default: npm
    default:  ERR!
    default:  A complete log of this run can be found in:
    default: npm
    default:  ERR!     /root/.npm/_logs/2019-06-12T14_29_52_616Z-debug.log
    default:  * Serving Flask app "server" (lazy loading)
    default:  * Environment: development
    default:  * Debug mode: on
    default: [INFO] [14:29:58:werkzeug]  * Running on http://0.0.0.0:7777/ (Press CTRL+C to quit)
    default: [INFO] [14:29:58:werkzeug]  * Restarting with stat
    default: Traceback (most recent call last):
    default:   File "server/atm_server/server.py", line 97, in <module>
    default:     start_server()
    default:   File "server/atm_server/server.py", line 92, in start_server
    default:     port=int(_args.port)
    default:   File "/vagrant/venv/lib/python3.5/site-packages/flask/app.py", line 941, in run
    default:     run_simple(host, port, self, **options)
    default:   File "/vagrant/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 1007, in run_simple
    default:     run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
    default:   File "/vagrant/venv/lib/python3.5/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    default:     sys.exit(reloader.restart_with_reloader())
    default:   File "/vagrant/venv/lib/python3.5/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    default:     exit_code = subprocess.call(args, env=new_environ, close_fds=False)
    default:   File "/usr/lib/python3.5/subprocess.py", line 557, in call
    default:     with Popen(*popenargs, **kwargs) as p:
    default:   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    default:     restore_signals, start_new_session)
    default:   File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    default:     raise child_exception_type(errno_num, err_msg)
    default: OSError: [Errno 8] Exec format error
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by makrasnov100** [comment]
I am receiving the same error when following the installation instructions on a Windows 10 machine.

After I see the error the virtual machine is up and running however I am unable to access the app from my browser. Installing `cross-env` on the vagrant machine manually by the first using `vagrant ssh` and then `sudo npm install --global cross-env` brings me a new error without the app running still.

**Comment by johnomahen79** [comment]
Cleaned out the whole ATMSeer directory, removed the VM and did a clean install. Now I do not even get the correct files on the VM...for example start.sh is no longer there along with no vagrant environment. Interesting

**Comment by johnomahen79** [comment]
I now got to the same error with cross environment error...
