### ISSUE TITLE
installation error on windows

### ISSUE THREAD

**Issue by whitewizard333** [HDI-Project/ATMSeer#26]
Getting following error while running install.sh script on windows. Any resolution for this?

default: npm
    default:  WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
    default: npm
    default: WARN
    default:  optional
    default:  SKIPPING OPTIONAL DEPENDENCY: minimist@1.2.0 (node_modules/fsevents/node_modules/rc/node_modules/minimist):
    default: npm
    default: WARN enoent
    default:  SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, open '/vagrant/node_modules/fsevents/node_modules/rc/node_modules/minimist/package.json.2605020691'
    default: npm WARN
    default:  optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
    default: npm WARN
    default:  notsup
    default:  SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    default: npm ERR!
    default:  Maximum call stack size exceeded
    default: npm
    default: ERR! A complete log of this run can be found in:
    default: npm ERR!     /root/.npm/_logs/2019-06-12T10_03_16_977Z-debug.log
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'ubuntu/xenial64' version '20190605.0.0' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 7777 (guest) => 7777 (host) (adapter 1)
    default: 7779 (guest) => 7779 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 5.1.38
    default: VirtualBox Version: 6.0
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/jmotwani/ATMSeer
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: vagrantstart (shell)...
    default: Running: C:/Users/jmotwani/AppData/Local/Temp/vagrant-shell20190612-164-1j9a70d.sh
    default: sh: 1: cross-env: not found
    default: npm
    default:
    default: ERR!
    default:
    default: file
    default:  sh
    default: npm
    default:
    default: ERR!
    default:
    default: code
    default:  ELIFECYCLE
    default: npm
    default:
    default: ERR!
    default:
    default: errno
    default:  ENOENT
    default: npm
    default:
    default: ERR!
    default:  syscall
    default:  spawn
    default: npm
    default: ERR!
    default:  vis_atm@0.1.0 start: `cross-env PORT=7779 react-scripts-ts start`
    default: npm
    default:
    default: ERR! spawn ENOENT
    default: npm
    default:  ERR!
    default:
    default: npm
    default:
    default: ERR!
    default:  Failed at the vis_atm@0.1.0 start script.
    default: npm
    default:
    default: ERR!
    default:  This is probably not a problem with npm. There is likely additional logging output above.
    default: npm ERR!
    default:  A complete log of this run can be found in:
    default: npm ERR!     /root/.npm/_logs/2019-06-12T10_03_53_255Z-debug.log
    default:  * Serving Flask app "server" (lazy loading)
    default:  * Environment: development
    default:  * Debug mode: on
    default: [INFO] [10:04:00:werkzeug]  * Running on http://0.0.0.0:7777/ (Press CTRL+C to quit)
    default: [INFO] [10:04:00:werkzeug]  * Restarting with stat
    default: Traceback (most recent call last):
    default:   File "server/atm_server/server.py", line 97, in <module>
    default:     start_server()
    default:   File "server/atm_server/server.py", line 92, in start_server
    default:     port=int(_args.port)
    default:   File "/vagrant/venv/lib/python3.5/site-packages/flask/app.py", line 941, in run
    default:     run_simple(host, port, self, **options)
    default:   File "/vagrant/venv/lib/python3.5/site-packages/werkzeug/serving.py", line 1007, in run_simple
    default:     run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
    default:   File "/vagrant/venv/lib/python3.5/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    default:     sys.exit(reloader.restart_with_reloader())
    default:   File "/vagrant/venv/lib/python3.5/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    default:     exit_code = subprocess.call(args, env=new_environ, close_fds=False)
    default:   File "/usr/lib/python3.5/subprocess.py", line 557, in call
    default:     with Popen(*popenargs, **kwargs) as p:
    default:   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    default:     restore_signals, start_new_session)
    default:   File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    default:     raise child_exception_type(errno_num, err_msg)
    default: OSError: [Errno 8] Exec format error
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by Hassan-Eldeeb** [comment]
Have you solved this problem ?
